version: '3.8'

services:
  frontend:
    container_name: CyLTour
    build:
      context: ./CyLTour
      dockerfile: Dockerfile
    volumes:
      - ./CyLTour:/app
    command: sh -c "npm install && npm run build"
    depends_on:
      - backend

  backend:
    container_name: CyLTourApi
    build:
      context: ./CyLTourApi
      dockerfile: Dockerfile
    volumes:
      - ./CyLTourApi:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db

  apache:
    image: httpd:2.4
    container_name: CyLTourApache
    ports:
      - "8000:80"
    volumes:
      - ./CyLTour/build:/var/www/CyLTour
      - ./CyLTourApi/public:/var/www/CyLTourApi
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache-config/vhosts:/usr/local/apache2/conf/vhosts:ro
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8
    container_name: CyLTourDB
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
