version: '3.8'

services:
  frontend:
    container_name: CyLTour
    build:
      context: ./CyLTour
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./CyLTour:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: CyLTourApi
    build:
      context: ./CyLTourApi
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./CyLTourApi:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:SomeFakeAppKeyChangeMe==
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: CyLTourDB
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
