services:
  frontend:
    build:
      context: ./CyLTour
    container_name: frontend
    ports:
      - 80:5173

  backend:
    build:
      context: ./CyLTourApi
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8081:80"
    volumes:
      - ./CyLTourApi:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
  
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: