services:
  frontend:
    build:
      context: ./CyLTour
    container_name: react_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./CyLTourApi
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8081:80"
    volumes:
      - ./CyLTourApi:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0.45
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
